# Generated by Django 4.1 on 2024-01-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_dependent'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='management_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='company.employee'),
        ),
    ]
